from typing import Dict, Any, List
from src.analysis.sentiment import SentimentEngine

class BotDetector:
    """
    detects if a post is likely generated by a bot or is low-quality spam.
    Also analyzes comments to verify 'Wisdom of Crowds'.
    """
    
    SPAM_KEYWORDS = [
        "crypto", "airdrop", "presale", "1000x", "gem", "whitelist", 
        "giveaway", "telegram", "whatsapp", "pump", "discord"
    ]
    
    def __init__(self):
        self.sentiment = SentimentEngine()

    def is_bot(self, post: Dict[str, Any]) -> bool:
        """
        Returns True if the post is suspicious.
        """
        content = post.get('content', '').lower()
        title = post.get('title', '').lower()
        score = post.get('score', 0)
        comments = post.get('comments', 0)
        
        # 1. Keyword Spam Check
        for keyword in self.SPAM_KEYWORDS:
            if keyword in content or keyword in title:
                return True
                
        # 2. Engagement Anomalies
        # High score but zero comments = Bot Upvote Farm
        if score > 100 and comments == 0:
            return True
            
        # 3. Low Effort
        # Very short content (unless it's a link/image post, which we can't easily distinguish just by text len)
        # But for 'dd' or 'discussion', short is bad.
        # We'll be conservative here.
        
        return False

    def verify_comments(self, comments: List[str]) -> float:
        """
        Analyzes sentiment of comments.
        Returns a 'Confirmation Score' (-1.0 to 1.0).
        Positive means comments agree with Bullish thesis (or are generally positive).
        Negative means comments are calling it out (Bearish).
        """
        if not comments:
            return 0.0
            
        total_score = 0
        count = 0
        
        for comment in comments:
            # Skip very short comments like "Nice" or "Lol"
            if len(comment) < 10:
                continue
                
            score = self.sentiment.analyze(comment)
            total_score += score['compound']
            count += 1
            
        if count == 0:
            return 0.0
            
        return total_score / count
